name: First Workflow
# workflow_dispatch = manual action
on: workflow_dispatch
jobs:
  first-job:
      runs-on: ubuntu-latest
      steps:
        - name: Print greeting
          run: echo "Hello World!"
        - name: Print goodbye
          run: echo "Done!"