name: Test Project
on:
  workflow_dispatch:
  push:
    branches:
      - main
env:
  MONGODB_DB_NAME: database_name
jobs:
    test:
        environment: testing
        env:
          MONGODB_CLUSTER_NAME: cluster_name
        runs-on: ubuntu-latest
        steps:
            - name: Get code from repo
              uses: actions/checkout@v3
            - name: Install NodeJS
              uses: actions/setup-node@v3
              with:
                node-version: 18
            - name: Cache dependencies
              uses: actions/cache@v3
              with:
                path: ~/.npm
                key: deps-node-modules-${{ hashFiles('**/package-lock.json') }}
            - name: Install dependencies
              run: npm ci
            - name: Run tests
              id: run-test
              run: npm test
            - name: Print cluster name
              run: echo ${{ env.MONGODB_CLUSTER_NAME }}
            - name: Print secret
              run: echo ${{ secrets.TESTING_SECRET }}
            - name: Upload test report
              if: failure() && steps.run-test.outcome == 'failure'
              uses: actions/upload-artifact@v3
              with:
                name: test-report
                path: test.json
    build:
        needs: test
        runs-on: ubuntu-latest
        outputs:
          script-file: ${{ steps.publish.outputs.script-file }}
        steps:
            - name: Get code from repo
              uses: actions/checkout@v3
            - name: Install NodeJS
              uses: actions/setup-node@v3
              with:
                node-version: 18
            - name: Cache dependencies
              uses: actions/cache@v3
              with:
                path: ~/.npm
                key: deps-node-modules-${{ hashFiles('**/package-lock.json') }}
            - name: Install dependencies
              run: npm ci
            - name: Build project
              run: npm run build
            - name: Get JS filename
              id: publish
              run: find dist/assets/*.js -type f -execdir echo 'script-file={}' >> $GITHUB_OUTPUT ';'
            - name: Upload artifact
              uses: actions/upload-artifact@v3
              with:
                name: dist-files
                path: |
                  dist
                  package.json
    deploy:
        needs: build
        runs-on: ubuntu-latest
        steps:
            - name: Get built artifact
              uses: actions/download-artifact@v3
              with:
                name: dist-files
            - name: Output contents
              run: ls -l
            - name: Output filename
              run: echo "${{ needs.build.outputs.script-file }}"
            - name: Deploy project
              run: echo "Deploying ..."
    report:
      needs: deploy
      if: failure()
      runs-on: ubuntu-latest
      steps:
        - name: output information
          run: |
            echo "Sth went wrong"
            echo "${{ toJson(github) }}"
