name: Test Project
on:
  pull_request:
    types:
      - opened
  workflow_dispatch:
  push:
    branches:
      - main
    paths-ignore:
      - '.github/workflows/*'
jobs:
    test:
        runs-on: ubuntu-latest
        steps:
            - name: Get code from repo
              uses: actions/checkout@v3
            - name: Install NodeJS
              uses: actions/setup-node@v3
              with:
                node-version: 18
            - name: Install dependencies
              run: npm ci
            - name: Run tests
              run: npm test
    deploy:
        needs: test
        runs-on: ubuntu-latest
        steps:
            - name: Get code from repo
              uses: actions/checkout@v3
            - name: Install NodeJS
              uses: actions/setup-node@v3
              with:
                node-version: 18
            - name: Install dependencies
              run: npm ci
            - name: Build project
              run: npm run build
            - name: Deploy
              run: echo "Deploying ..." 
